config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => "/cable"
  scope "(:locale)", locale: /en|vn/ do
    devise_for :users
    root "homepages#home"
    resources :users, only: %i(show edit update destroy)
    resources :companies do
      resources :employees
      resources :buses
      resources :routes
      resources :trips do
        member do
          get :export
          get :download, to: "downloads#show"
        end
        collection do
          match 'search' => 'trips#search', :via => [:get, :post], :as => :search
        end
        resources :bookings, only: %i(show update create)
        # resources :downloads, only: %i(show)
      end
      resources :notifications
    end
  end
  put "/accept/bookings/:id", to: "bookings#accept", as: "accept_booking"
  put "/reject/bookings/:id", to: "bookings#reject", as: "reject_booking"
  namespace :api do
    post "/history-bookings", to: "bookings#index"
    post "/bookings", to: "bookings#create"
    get "/bookings/:id", to: "bookings#show"
    delete "/bookings/:id", to: "bookings#destroy"
    get "/trips", to: "trips#index"
    get "/trips/:id", to: "trips#show"
    post "/trips/search", to: "trips#search"
    get "/routes", to: "routes#index"
    get "/routes/:id", to: "routes#show"
    get "/companies", to: "companies#index"
  end
  match '*path' => "errorpage#not_found", via: :get
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company

  has_many :trips

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true
  enum role: %i(major minor)
  enum status: %i(ready busy)

  scope :is_ready, ->{where(status: :ready)}
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource
  # before_action :authenticate_user!
  before_action :load_company
  before_action :load_notifications

  def index
    @employees = current_user.company.employees
  end

  def show
    if @employee.major?
      @trips = Trip.trips_of_driver_major(@employee.id)
    elsif @employee.minor?
      @trips = Trip.trips_of_driver_minor(@employee.id)
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = @company.employees.build employee_params
    if @employee.save
      flash[:success] = t(".success")
      redirect_to company_employees_path
    else
      flash[:error] = t(".error")
      render :new
    end
  end

  def edit
  end

  def update

  end

  private

  def employee_params
    params.require(:employee).permit(:name, :address, :role, :avatar).merge! company_id: current_user.company.id
  end

  def load_company
    @company = current_user.company
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<tr class="even pointer">
  <td class=" "><%= employee.name %></td>
  <td class=" "><%= employee.address %> </td>
  <td class=" "><%= Employee.human_enum_name(:role, employee.role) %></td>
  <td class=" last">
    <%= link_to t(".detail"), company_employee_path(current_user.company,employee), class: "btn btn-primary btn-xs"  %>
    <%= link_to t(".edit"), edit_company_employee_path(current_user.company,employee), class: "btn btn-info btn-xs"  %>
  </td>
</tr>

app/views/employees/_form.html.erb
<%= simple_form_for [@company,@employee], html: {class: "col-md-6 offset-md-3"} do |f| %>
    <%= f.input :name, class: "col-md-6 col-sm-6 form-control" %>
    <%= f.input :address, class: "col-md-6 col-sm-6 form-control" %>
    <%= f.input :role, as: :select, include_blank: false, collection: enum_options_for_select(Employee, :role), class: "col-md-6 col-sm-6 form-control" %>
    <%= f.input :avatar, class: "col-md-6 col-sm-6 form-control" %>
    <% if @employee.avatar? %>
      <%= image_tag @employee.avatar.url, id: "img_avatar", width: "200", height: "auto" %>
    <% else %>
      <%= image_tag "/assets/default-image.jpg", id: "img_avatar", width: "200", height: "auto" %>
    <% end %>

  <div class="ln_solid"></div>
  <div class="item form-group">
    <div class="col-md-6 col-sm-6 offset-md-3">
      <button class="btn btn-primary" type="reset"><%= t("reset") %></button>
      <button type="submit" class="btn btn-success"><%= t("submit") %></button>
    </div>
  </div>
<% end %>
<%= javascript_include_tag "show_image.js" %>

app/views/employees/_trip.html.erb
<% trips.each do |trip| %>
  <li>
    <div class="message_date">
      <h3 class="date text-info"><%= trip.start_time.day %></h3>
      <p class="month"><%= l trip.start_time, format: "%B" %></p>
    </div>
    <div class="message_wrapper">
      <h4 class="heading"><%= trip.route.start_place %> <%= t(".to") %> <%= trip.route.end_place %></h4>
      <blockquote class="message"><%= t(".driver_major") %>: <%= trip.driver_major.name %></blockquote>
      <blockquote class="message"><%= t(".driver_minor") %>: <%= trip.driver_minor.name %></blockquote>
      <br />
    </div>
  </li>
<% end %>

app/views/employees/index.html.erb
<div class="right_col" role="main">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t(".employee") %></h3>
    </div>
  </div>

<div class="clearfix"></div>
<div class="row">
  <div class="col-md-8 col-sm-8 col-xs-8 offset-md-2">
    <div class="x_panel">
      <div class="x_title">
        <ul class="nav navbar-right panel_toolbox">
          <li>
            <%= button_to t(".add"), new_company_employee_path, method: :get, class: "btn btn-success btn-xs" %>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <% if @employees.present? %>
          <table id ="data-employees" class="table table-striped jambo_table bulk_action">
            <thead>
              <tr class="headings">
                <th class="column-title"><%= t(".name") %> </th>
                <th class="column-title"><%= t(".address") %> </th>
                <th class="column-title"><%= t(".role") %> </th>
                <th class="column-title no-link last">
                  <span class="nobr"><%= t(".action") %></span>
                </th>
              </tr>
            </thead>
            <tbody>
              <%= render @employees %>
            </tbody>
          </table>
        <% else %>
          <p class="text-center"><%= t("no_data") %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "search_employees" %>

app/views/employees/new.html.erb
<div class="right_col" role="main">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t(".employee") %></h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 ">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t(".create") %></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div class="right_col" role="main">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t(".bus") %></h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 ">
      <div class="x_panel">
        <div class="x_content">
          <div class="col-md-3 col-sm-3  profile_left">
            <ul class="list-unstyled user_data">
              <li>
                <i class="fa fa-user"></i> <%= t(".name") %>: <%= @employee.name %>
              </li>
              <li>
                <i class="fa fa-phone"></i> <%= t(".phone") %>: <%= @employee.phone %>
              </li>
              <li>
                <i class="fa fa-location-arrow"></i> <%= t(".address") %>: <%= @employee.address %>
              </li>
              <li>
                <i class="fa fa-user"></i> <%= t(".role") %>: <%= Employee.human_enum_name(:role, @employee.role) %>
              </li>
            </ul>
            <br />
          </div>
          <div class="col-md-9 col-sm-9 ">
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
              <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                <li role="presentation" class="active"><a href="" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true"><%= t(".list_trips") %></a>
                </li>
              </ul>
              <div id="myTabContent" class="tab-content">
                <div role="tabpanel" class="tab-pane active " id="tab_content1" aria-labelledby="home-tab">
                  <!-- start recent activity -->
                  <ul class="messages">
                    <% if @trips.size%>
                      <%= render partial: "trip", locals: {trips: @trips }%>
                    <% else %>
                      <p style="text-align:center"><%= t(".no_data") %></p>
                    <% end %>
                  </ul>
                  <!-- end recent activity -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>