config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => "/cable"
  scope "(:locale)", locale: /en|vn/ do
    devise_for :users
    root "homepages#home"
    resources :users, only: %i(show edit update destroy)
    resources :companies do
      resources :employees
      resources :buses
      resources :routes
      resources :trips do
        member do
          get :export
          get :download, to: "downloads#show"
        end
        collection do
          match 'search' => 'trips#search', :via => [:get, :post], :as => :search
        end
        resources :bookings, only: %i(show update create)
        # resources :downloads, only: %i(show)
      end
      resources :notifications
    end
  end
  put "/accept/bookings/:id", to: "bookings#accept", as: "accept_booking"
  put "/reject/bookings/:id", to: "bookings#reject", as: "reject_booking"
  namespace :api do
    post "/history-bookings", to: "bookings#index"
    post "/bookings", to: "bookings#create"
    get "/bookings/:id", to: "bookings#show"
    delete "/bookings/:id", to: "bookings#destroy"
    get "/trips", to: "trips#index"
    get "/trips/:id", to: "trips#show"
    post "/trips/search", to: "trips#search"
    get "/routes", to: "routes#index"
    get "/routes/:id", to: "routes#show"
    get "/companies", to: "companies#index"
  end
  match '*path' => "errorpage#not_found", via: :get
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_company
  before_action :load_notifications

  def home
    @count_paying = 0
    @count_paid = 0
    if @company.present?
      @trips = @company.trips
      @trips.each do |trip|
        @count_paying += trip.bookings.paying.size
        @count_paid += trip.bookings.paid.size
      end
    end
    if current_user.admin?
      @users = User.non_admin
    end
  end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
  def unread_notification company
    @company = company
    return 0 unless @company.present?
    @company.notifications.unread.size
  end
end

app/views/homepages/_data_company.html.erb
<div class="row tile_count">
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
      <span class="count_top"><i class="fa fa-user"></i> <%= t(".total_employees") %></span>
      <div class="count"><%= company.present? ? company.employees.size : 0 %></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
      <span class="count_top"><i class="fa fa-random"></i> <%= t(".total_routes") %></span>
      <div class="count"><%= company.present? ? company.routes.size : 0 %></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
      <span class="count_top"><i class="fa fa-road"></i> <%= t(".total_trips") %></span>
      <div class="count green"><%= company.present? ? company.trips.size : 0 %></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
      <span class="count_top"><i class="fa fa-bus"></i> <%= t(".total_buses") %></span>
      <div class="count"><%= company.present? ? company.buses.size : 0 %></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
      <span class="count_top"><i class="fa fa-ticket"></i> <%= t(".total_booking") %></span>
      <div class="count"><%= count_paying %></div>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
      <span class="count_top"><i class="fa fa-ticket"></i> <%= t(".total_payed") %></span>
      <div class="count"><%= count_paid %></div>
    </div>
  </div>

app/views/homepages/_user.html.erb
<% @users.each_with_index do |user, index| %>
  <tr class="headings">
    <td class="vertical-align-mid text-center"><%= index + 1 %></td>
    <td class="vertical-align-mid text-center"><%= user.fullname %></td>
    <td class="vertical-align-mid text-center"><%= user.phone %></td>
    <td class="vertical-align-mid text-center"><%= user.company.present? ? user.company.name : t(".no_company") %></td>
    <td class="vertical-align-mid text-center"><%= user.company.present? ? user.company.buses.size : 0 %></td>
    <td class="vertical-align-mid text-center"><%= user.company.present? ? user.company.employees.size : 0 %></td>
    <td class="vertical-align-mid text-center"><%= user.company.present? ? user.company.routes.size : 0 %></td>
    <td class="vertical-align-mid text-center"><%= user.company.present? ? user.company.trips.size : 0 %></td>
    <td class="vertical-align-mid text-center"><%= l user.created_at, format: Settings.format_time.long %></td>
    <td class="vertical-align-mid text-center">
      <%= link_to t(".delete"), user_path(user), class: "btn btn-danger btn-xs", method: :delete, data: {confirm: t("sure")} %>
    </td>
  </tr>
<% end %>

app/views/homepages/_users.html.erb
<div class="x_content">
  <div class="table-responsive">
    <table class="table table-striped jambo_table bulk_action">
      <thead>
        <tr class="headings">
          <th class="column-title" style="text-align:center"><%= t("number_order") %> </th>
          <th class="column-title" style="text-align:center"><%= t(".username") %> </th>
          <th class="column-title" style="text-align:center"><%= t(".phone") %> </th>
          <th class="column-title" style="text-align:center"><%= t(".company_name") %> </th>
          <th class="column-title" style="text-align:center"><%= t(".count_buses") %> </th>
          <th class="column-title" style="text-align:center"><%= t(".count_employees") %> </th>
          <th class="column-title" style="text-align:center"><%= t(".count_routes") %> </th>
          <th class="column-title" style="text-align:center"><%= t(".count_trips") %></th>
          <th class="column-title" style="text-align:center"><%= t(".created_at") %> </th>
          <th class="column-title no-link last" style="text-align:center">
            <span class="nobr"><%= t("action") %></span>
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "user", locals: {companies: @users} %>
      </tbody>
    </table>
  </div>
</div>

app/views/homepages/home.html.erb
<div class="right_col" role="main">
  <% if !current_user.admin? %>
    <%= render partial: "data_company", locals: {company: @company, count_paying: @count_paying, count_paid: @count_paid} %>
  <% end %>
    <!-- /top tiles -->
  <div class="row">
    <% if current_user.editor? %>
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="dashboard_graph">
        <% if current_user.company.present? %>
          <div class="row x_title">
            <div class="col-md-6">
              <h3><%= t(".company") %><small> <%= @company.name %></small></h3>
              <%= link_to t(".edit"), edit_company_path(@company), class: "btn btn-primary" %>
            </div>
            <div class="col-md-6">
            <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
              <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
              <span><%= l(Time.zone.now, format: :full) %> <b class="caret"></b>
            </div>
          </div>
        </div>
          <div class="col-md-9 col-sm-9 col-xs-12">
            <% if current_user.company.banner.present? %>
              <%= image_tag current_user.company.banner.url, style:"width:100%;height:auto" %>
            <% else %>
              <%= image_tag "default-image.jpg", style:"width:100%;height:auto" %>
            <% end %>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-12 bg-white">
            <div class="x_title">
              <h2><%= t(".info") %></h2>
              <div class="clearfix"></div>
            </div>
              <div class="col-md-12 col-sm-12 col-xs-6">
                <div>
                  <p><%= raw @company.company_info %></p>
                </div>
                <div>
                  <p class="fa fa-location-arrow"> <%= t(".address") %>: <%= @company.address %></p>
                  <p class="fa fa-phone"> <%= t(".phone") %>: <%= @company.phone %></p>
                </div>
              </div>
              <div class="clearfix"></div>
          </div>
          <div class="clearfix"></div>
          </div>
        <% end %>
      </div>
    <% else %>
      <%= render partial: "users", locals: {users: @users} %>
    <% end %>
    <br>
  </div>
</div>