config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => "/cable"
  scope "(:locale)", locale: /en|vn/ do
    devise_for :users
    root "homepages#home"
    resources :users, only: %i(show edit update destroy)
    resources :companies do
      resources :employees
      resources :buses
      resources :routes
      resources :trips do
        member do
          get :export
          get :download, to: "downloads#show"
        end
        collection do
          match 'search' => 'trips#search', :via => [:get, :post], :as => :search
        end
        resources :bookings, only: %i(show update create)
        # resources :downloads, only: %i(show)
      end
      resources :notifications
    end
  end
  put "/accept/bookings/:id", to: "bookings#accept", as: "accept_booking"
  put "/reject/bookings/:id", to: "bookings#reject", as: "reject_booking"
  namespace :api do
    post "/history-bookings", to: "bookings#index"
    post "/bookings", to: "bookings#create"
    get "/bookings/:id", to: "bookings#show"
    delete "/bookings/:id", to: "bookings#destroy"
    get "/trips", to: "trips#index"
    get "/trips/:id", to: "trips#show"
    post "/trips/search", to: "trips#search"
    get "/routes", to: "routes#index"
    get "/routes/:id", to: "routes#show"
    get "/companies", to: "companies#index"
  end
  match '*path' => "errorpage#not_found", via: :get
end

app/models/notification.rb
class Notification < ApplicationRecord
  after_create_commit :push_notify
  belongs_to :company

  scope :newest, ->{order(created_at: :desc)}
  scope :unread, ->{where(status: :unread)}

  enum status: %i(unread readed)

  private

  def push_notify
    ActionCable.server.broadcast "notification_channel", notification: render_notification(self)
  end

  def render_notification notification
    ApplicationController.renderer.render partial: "notifications/notification", locals: {notification: notification}
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_company

  def index
    @notifications = @company.notifications.newest.page(params[:page]).per(10)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def load_trip id
    @trip = Trip.find_by id: id
    return @trip if @trip.present?
  end
end

app/views/notifications/_notification.html.erb
<li class="nav-item notify-<%= notification.status %>">
  <span class="message">
      <%= link_to notification.content, company_trip_path(notification.company,load_trip(notification.url_id), notify_id: notification.id), class: "dropdown-item" %>
  </span>
</li>

app/views/notifications/_notification_list.html.erb
<% notifications.each do |notification| %>
  <li class="notify-<%= notification.status %>" id="<%= notification.id %>">
    <div class="message_wrapper">
      <blockquote class="message"><%= link_to notification.content, company_trip_path(notification.company,load_trip(notification.url_id), notify_id: notification.id) %></blockquote>
      <br />
    </div>
  </li>
<% end %>

app/views/notifications/_notifications.html.erb
<%= render partial: "notifications/notification", collection: @notifications, as: :notification %>

app/views/notifications/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t(".notifications") %></h3>
      </div>

    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12">
        <div class="x_panel">
          <div class="x_title">

            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="col-md-9 col-sm-9 col-xs-12">
                <h4>Recent Activity</h4>
                <!-- end of user messages -->
                <ul class="messages">
                  <%= render partial: "notifications/notification_list", locals: {notifications: @notifications} %>
                </ul>
                <!-- end of user messages -->
                <%= paginate @notifications %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>