config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => "/cable"
  scope "(:locale)", locale: /en|vn/ do
    devise_for :users
    root "homepages#home"
    resources :users, only: %i(show edit update destroy)
    resources :companies do
      resources :employees
      resources :buses
      resources :routes
      resources :trips do
        member do
          get :export
          get :download, to: "downloads#show"
        end
        collection do
          match 'search' => 'trips#search', :via => [:get, :post], :as => :search
        end
        resources :bookings, only: %i(show update create)
        # resources :downloads, only: %i(show)
      end
      resources :notifications
    end
  end
  put "/accept/bookings/:id", to: "bookings#accept", as: "accept_booking"
  put "/reject/bookings/:id", to: "bookings#reject", as: "reject_booking"
  namespace :api do
    post "/history-bookings", to: "bookings#index"
    post "/bookings", to: "bookings#create"
    get "/bookings/:id", to: "bookings#show"
    delete "/bookings/:id", to: "bookings#destroy"
    get "/trips", to: "trips#index"
    get "/trips/:id", to: "trips#show"
    post "/trips/search", to: "trips#search"
    get "/routes", to: "routes#index"
    get "/routes/:id", to: "routes#show"
    get "/companies", to: "companies#index"
  end
  match '*path' => "errorpage#not_found", via: :get
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  load_and_authorize_resource
  before_action :load_company
  before_action :load_notifications

  def index
    @buses = current_user.company.buses.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @bus = Bus.new
  end

  def create
    @bus = @company.buses.build bus_params
    #Check type quality
    if @bus.normal?
      @bus.slot = 46
    elsif @bus.vip?
      @bus.slot = 36
    end

    if @bus.save
      flash[:success] = t ".success"
      redirect_to company_buses_path
    else
      flash[:error] = t ".error"
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def bus_params
    params.require(:bus).permit(:license_plate, :type_quality).merge! company_id: current_user.company.id
  end


end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_bus.html.erb
<tr class="even pointer">
  <td class=" "><%= bus.license_plate %></td>
  <td class=" "><%= Bus.human_enum_name(:type_quality, bus.type_quality) %></td>
  <td class=" "><%= bus.slot %> </td>
  <td class=" last">
    <%= link_to t(".detail"), company_bus_path(current_user.company,bus), class: "btn btn-primary btn-xs"  %>
    <% if bus.trips.blank? %>
      <%= link_to t(".edit"), edit_company_bus_path(current_user.company,bus), class: "btn btn-info btn-xs"  %>
    <% end %>
  </td>
</tr>

app/views/buses/_form.html.erb
<%= simple_form_for [@company,@bus], html: {class: "col-md-6 offset-md-3"} do |f| %>
  <%= f.input :license_plate, class: "col-md-6 col-sm-6 form-control" %>
  <%= f.input :type_quality, as: :select, include_blank: false, collection: enum_options_for_select(Bus, :type_quality), class: "col-md-6 col-sm-6 form-control" %>
  <div class="ln_solid"></div>
  <div class="item form-group">
    <div class="col-md-6 col-sm-6 offset-md-3">
      <button class="btn btn-primary" type="reset"><%= t("reset") %></button>
      <button type="submit" class="btn btn-success"><%= t("submit") %></button>
    </div>
  </div>
<% end %>

app/views/buses/edit.html.erb
<div class="right_col" role="main">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t(".bus") %></h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 ">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t(".create") %></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buses/index.html.erb
<div class="right_col" role="main">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t(".bus") %></h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-8 col-sm-8 col-xs-8 offset-md-2">
      <div class="x_panel">
        <div class="x_title">
          <ul class="nav navbar-right panel_toolbox">
            <li>
              <%= button_to t(".add"), new_company_bus_path, method: :get, class: "btn btn-success btn-xs" %>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action">
              <thead>
                <tr class="headings">
                  <th class="column-title"><%= t(".license_plate") %> </th>
                  <th class="column-title"><%= t(".type_quality") %> </th>
                  <th class="column-title"><%= t(".slot") %> </th>
                  <th class="column-title no-link last">
                    <span class="nobr"><%= t("action") %></span>
                  </th>
                </tr>
              </thead>
              <tbody>
                <%= render @buses %>
              </tbody>
            </table>
            <%= paginate @buses %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buses/new.html.erb
<div class="right_col" role="main">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t(".bus") %></h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 ">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t(".create") %></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buses/show.html.erb
<div class="right_col" role="main">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t(".bus") %></h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 ">
      <div class="x_panel">
        <div class="x_content">
          <div class="col-md-3 col-sm-3  profile_left">
            <ul class="list-unstyled user_data">
              <li>
                <i class="fa fa-bus"></i> <%= t(".license_plate") %>: <%= @bus.license_plate %>
              </li>
              <li>
                <i class="fa fa-wheelchair"></i> <%= t(".seats") %>: <%= @bus.slot %>
              </li>
            </ul>
            <br />
          </div>
          <div class="col-md-9 col-sm-9 ">
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
              <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                <li role="presentation" class="active"><a href="" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true"><%= t(".list_trips") %></a>
                </li>
              </ul>
              <div id="myTabContent" class="tab-content">
                <div role="tabpanel" class="tab-pane active " id="tab_content1" aria-labelledby="home-tab">
                  <!-- start recent activity -->
                  <ul class="messages">
                    <% if @bus.trips.size > 0 %>
                      <%= render partial: "trip", locals: {trips: @bus.trips }%>
                    <% else %>
                      <p style="text-align:center"><%= t(".no_data") %></p>
                    <% end %>
                  </ul>
                  <!-- end recent activity -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>